### ISSUE TITLE
uploading the same file more than once

### ISSUE THREAD

**Issue by roozbehmeghdadi** [yyassif/uppy-supabase-nextjs#1]
Hi, your work here is excellent. Thank you for sharing. I've been trying to use it, and it works for the most part. However, I'm having issues getting it to upload the same again with a new name. I even generated a new file name and meta data. Is that a superbase-related issue, a Tu's issue, or does something else need to change in the code to allow for that?

any help would be greatly appreciate it. 
thank you 

`function generateUniqueFileName(file: { name: string }): string {
  const fileName = file.name
    .split(".")
    .slice(0, -1)
    .join(".")
    .replace(/ /g, "_");
  const extension = file.name.split(".").pop();
  const uniqueId = uuidv4();
  return `${uniqueId}_${fileName}.${extension}`;
}`
`export const UppyProvider: React.FC<UppyProviderProps> = ({ children }) => {
  const [uppy] = useState(() =>
    new Uppy({
      meta: {
        uniqueId: uuidv4(), 
      },
    }).use(Tus, {
      endpoint: UPPY_TUS_ENDPOINT,
      headers: {
        Authorization: "Bearer " + process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
      },
      allowedMetaFields: [
        "bucketName",
        "uniqueId",
        "objectName",
        "contentType",
        "cacheControl",
      ],
    })
  );

  uppy.on("file-added", (file) => {
    const objectName = generateUniqueFileName(file);
    console.log(`File added with generated object name: ${objectName}`); 
    file.meta = {
      ...file.meta,
      uniqueId: uuidv4(), 
      bucketName: UPPY_BUCKET,
      objectName,
      contentType: file.type,
      name: objectName,
      cacheControl: "no-cache",
    };
    console.log(`File meta updated: `, file.meta); 
  });`

**Comment by yyassif** [comment]
Hey pal, sorry for the late response,
Well that's an issue related to supabase itself.
For instance if you're using the client wrapper here is how you can upsert files:

```tsx
// Create Supabase client
const supabase = createClient('your_project_url', 'your_supabase_api_key')

await supabase.storage.from('bucket_name').upload('file_path', file, {
  upsert: true,
})
```

On the other hand, if you're using the storage API,  you can add the following property `"x-upsert": true` to the headers object of your request.

Another way to overwriting files using the upsert functionality you will need to additionally grant SELECT and UPDATE permissions.

```sql
create policy "Anyone can select the bucket" on storage.objects for select to authenticated with check ( bucket_id = 'bucket_id' );
create policy "Anyone can update the bucket." on storage.objects for update to authenticated with check ( bucket_id = 'bucket_id' );
```

The last approach is a bit risky cuz it give full access to the bucket, you need to ensure auth users like I did and check their RBAC if they're authorized to make the update.

**Comment by roozbehmeghdadi** [comment]
Thank you so much; that is beneficial information. I appreciate the suggestions.
